# Generated by Django 5.1.2 on 2024-10-31 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='LiturgicalTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tempo Liturgico')),
            ],
        ),
        migrations.CreateModel(
            name='Chord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='')),
                ('pdf_file', models.FileField(upload_to='pdf', verbose_name='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chords.category', verbose_name='')),
                ('liturgical_time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chords.liturgicaltime', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Mass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='')),
                ('acclaim', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='acclaim_chord', to='chords.chord', verbose_name='')),
                ('communion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='communion_chord', to='chords.chord', verbose_name='')),
                ('entrance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entrance_chord', to='chords.chord', verbose_name='')),
                ('final', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='final_chord', to='chords.chord', verbose_name='')),
                ('generic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='generic_chord', to='chords.chord', verbose_name='')),
                ('glory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='glory_chord', to='chords.chord', verbose_name='')),
                ('holy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='holy_chord', to='chords.chord', verbose_name='')),
                ('offertory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='offertory_chord', to='chords.chord', verbose_name='')),
                ('penitential', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='penitential_chord', to='chords.chord', verbose_name='')),
                ('post_communion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='post_communion_chord', to='chords.chord', verbose_name='')),
            ],
        ),
    ]
